accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('novo-usuario/', views.addUser, name='addUser'),
    path('minha-conta/', views.myAccount, name='myAccount'),
    path('atualizar-dados/', views.updateUser, name='updateUser'),
    path('atualizar-senha/', views.updatePassword, name='updatePassword'),

]

iscool/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static

from core import views
from post import urls as post_urls
from accounts import urls as accounts_urls
from discipline import urls as discipline_urls
from material import urls as material_urls

urlpatterns = [
    path('',views.index, name='index'),
    path('erro',views.erro404, name='error'),

    path('admin/', admin.site.urls),
    path('postar/',include(post_urls)),
    path('conta/',include(accounts_urls)),
    path('disciplina/',include(discipline_urls)),
    path('material/',include(material_urls)),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'login'}, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [

    path('novo-topico/', views.newTopic, name="newTopic"),
    path('nova-resposta/', views.newReply, name="newReply"),
    path('editar-topico/(?P<id>[0-9]+)/', views.editTopic, name="editTopic"),
    path('editar-comentario/(?P<id>[0-9]+)/', views.editReply, name="editReply"),
    path('deletar-topico/(?P<id>[0-9]+)/', views.deleteTopic, name="deleteTopic"),
    path('deletar-comentario/(?P<id>[0-9]+)/', views.deleteReply, name="deleteReply"),

]

accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

# Create your models here.

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de Usuário Válido. '
                'Este valor deve conter apenas letras e números.'
                'e os caracteres: @/./+/-/_.'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail')
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    is_student = models.BooleanField('Aluno', default=False)
    is_moderator = models.BooleanField('Moderador', default=False)
    is_teacher = models.BooleanField('Professor', default=False)

    avatar = models.ImageField('Avatar', upload_to='avatars', blank='true', default='avatars/user.png')


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        # permissions = (
        #     ('teacher', 'professor'),
        #     ('moderator', 'moderador'),
        #     ('student', 'aluno'),
        # )

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User

class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','name','email','is_student','is_teacher','avatar']

class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, TemplateView, UpdateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm


from django.contrib.auth import authenticate
from django.contrib.auth import login

from .models import User
from .forms import UserAdminCreationForm
# Create your views here.

class RegisterView(CreateView):

    model = User
    template_name = "accounts/add_user.html"
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        is_valid = form.is_valid()
        response = super().post(request, *args, **kwargs)
        if is_valid:
            new_user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
            )
            login(request, new_user)
            return HttpResponseRedirect(reverse_lazy('index'))
        return response

class MyAccountView(LoginRequiredMixin, TemplateView):

    template_name = "accounts/minha-conta.html"

class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update-user.html'
    fields = ['name', 'email', 'avatar']
    success_url = reverse_lazy('accounts:myAccount')


    def get_object(self):
        return self.request.user

class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update-password.html'
    success_url = reverse_lazy('accounts:myAccount')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)


updateUser = UpdateUserView.as_view()
addUser = RegisterView.as_view()
myAccount = MyAccountView.as_view()
updatePassword = UpdatePasswordView.as_view()

accounts/templates/accounts/add_user.html
{% extends "base_accounts.html" %}
{% load widget_tweaks %}
{% load static %}


{% block title %}Cadastro de Usuário{% endblock %}

{% block container %}

<div class="box">
  <img class="mb-4" src="{% static "img/logo.png" %}" alt="" width="" height="">
  <p class="display-4">Cadastre-se</p>

  {% for error in form.non_field_errors %}
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{error}}
    </div>
  {% endfor %}
  {% for error in form.errors %}
    {{error}}
  {% endfor %}

  <ul class="nav nav-pills nav-justified" role="tablist" id="tab-choice">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#add_student" role="tab">Sou Aluno</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#add_teacher" role="tab" >Sou Professor</a>
    </li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane fade show active" id="add_student" role="tabpanel" >

      <form class="form-box" action="" method="post">
        {% csrf_token %}


        {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

          {% render_field form.username class='form-control' placeholder='Nome de Usuário' %}
          {% render_field form.name class='form-control' placeholder='Nome Completo' %}
          {% render_field form.email class='form-control' placeholder='E-mail' %}
          {% render_field form.password1 class='form-control' placeholder='Senha' %}
          {% render_field form.password2 class='form-control' placeholder='Confirmação da Senha' %}


          <input type="hidden" name="is_student" value="1">



        {% endwith %}

        <button type="submit" class="btn btn-success">Cadastrar</button>
        <a href="{% url 'login' %}" class="btn btn-secondary">Já Tenho Cadastro</a>
        <hr>
        <button class="btn btn-warning btn-block">Como funciona o isCool?</button>

      </form>

    </div>


    <div class="tab-pane fade" id="add_teacher" role="tabpanel" >

      <form class="form-box" action="" method="post">
        {% csrf_token %}


        {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

          {% render_field form.username class='form-control' placeholder='Nome de Usuário' %}
          {% render_field form.name class='form-control' placeholder='Nome Completo' %}
          {% render_field form.email class='form-control' placeholder='E-mail' %}
          {% render_field form.password1 class='form-control' placeholder='Senha' %}
          {% render_field form.password2 class='form-control' placeholder='Confirmação da Senha' %}


          <input type="hidden" name="is_teacher" value="1">



        {% endwith %}

        <button type="submit" class="btn btn-success">Cadastrar</button>
        <a href="{% url 'login' %}" class="btn btn-secondary">Já Tenho Cadastro</a>
        <hr>
        <button class="btn btn-warning btn-block">Como funciona o isCool?</button>

      </form>


    </div>
  </div>
</div>






{% endblock %}

accounts/templates/accounts/login.html
{% extends "base_accounts.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Auntenticação de Usuário{% endblock %}

{% block container %}
  <form class="form-box" method="post">

    {% csrf_token %}

    <img class="mb-4" src="{% static "img/logo.png" %}" alt="" width="" height="">
    <p class="display-4">Entre</p>

    {% for error in form.non_field_errors %}
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{error}}
      </div>
    {% endfor %}

    {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

          {% render_field form.username class='form-control' placeholder='Nome de Usuário' %}

          {% render_field form.password class='form-control' placeholder='Senha' %}

    {% endwith %}


    <button class="btn btn-primary" type="submit">Entrar</button>
    <a href="{% url 'accounts:addUser' %}" class="btn btn-secondary">Não Tenho Cadastro</a>
  </form>

{% endblock %}

accounts/templates/accounts/minha-conta.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<div class="container margin-top">
  <div class="row">
      <div class="col-md-4">
          <div class="list-group">
            <a href="#" class="list-group-item active">Minha Conta</a>
            <a href="{% url 'accounts:updateUser' %}" class="list-group-item">Alterar Dados</a>
            <a href="{% url 'accounts:updatePassword' %}" class="list-group-item">Alterar Senha</a>
          </div>
      </div>
      <div class="col-md-8">
        {% block accounts_container %}{% endblock %}
      </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/update-password.html
{% extends "accounts/minha-conta.html" %}
{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
  <form class="" method="post">
    <h2>Alterar Senha</h2>
    {% csrf_token %}

    {{form}}

    <button class="btn btn-primary" type="submit">Alterar</button>
  </form>
{% endblock %}

accounts/templates/accounts/update-user.html
{% extends "accounts/minha-conta.html" %}
{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
  <form class="" method="post" enctype="multipart/form-data">
    <h2>Alterar Dados</h2>
    {% csrf_token %}

    {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

          {% render_field form.name class='form-control' placeholder='Nome de Usuário' %}

          {% render_field form.email class='form-control' placeholder='Senha' %}

          {% render_field form.avatar %}


    {% endwith %}


    <button class="btn btn-primary" type="submit">Alterar</button>
  </form>
{% endblock %}