discipline/urls.py
from django.urls import path

from . import views

app_name = 'discipline'
urlpatterns = [
    path('ver-disciplinas/', views.listDiscipline, name="listDiscipline"),

    path('adicionar-disciplina/', views.addDiscipline, name="addDiscipline"),
    path('mudar-estado/(?P<id>[0-9]+)/', views.registerStudent, name="registerStudent"),
    path('editar-disciplina/(?P<id>[0-9]+)/', views.editDiscipline, name="editDiscipline"),
    path('gerenciar-alunos/', views.listStudent, name="listStudent"),
    path('gerenciar-disciplina/', views.managerDiscipline, name="managerDiscipline"),
    path('deletar-disciplina/(?P<id>[0-9]+)/', views.deleteDiscipline, name="deleteDiscipline"),

]

iscool/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static

from core import views
from post import urls as post_urls
from accounts import urls as accounts_urls
from discipline import urls as discipline_urls
from material import urls as material_urls

urlpatterns = [
    path('',views.index, name='index'),
    path('erro',views.erro404, name='error'),

    path('admin/', admin.site.urls),
    path('postar/',include(post_urls)),
    path('conta/',include(accounts_urls)),
    path('disciplina/',include(discipline_urls)),
    path('material/',include(material_urls)),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'login'}, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [

    path('novo-topico/', views.newTopic, name="newTopic"),
    path('nova-resposta/', views.newReply, name="newReply"),
    path('editar-topico/(?P<id>[0-9]+)/', views.editTopic, name="editTopic"),
    path('editar-comentario/(?P<id>[0-9]+)/', views.editReply, name="editReply"),
    path('deletar-topico/(?P<id>[0-9]+)/', views.deleteTopic, name="deleteTopic"),
    path('deletar-comentario/(?P<id>[0-9]+)/', views.deleteReply, name="deleteReply"),

]

discipline/models.py
from django.db import models

# Create your models here.

class Discipline(models.Model):

    teacher = models.ForeignKey('accounts.User', verbose_name='Professor(a)', on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=25)
    description = models.TextField('Descição')

    class Meta:
        verbose_name = 'Disciplina'
        verbose_name_plural = 'Disciplinas'

    def __str__(self):
        return self.name

class RegisterStudent(models.Model):
    STATUS_CHOICE = (
        (0, 'Aguardando Confirmação'),
        (1, 'Adicionado na Disciplina'),
        (2, 'Solicitação Recusada'),
        (3, 'Administrador'),

    )

    class Meta:
        verbose_name = 'Registro'
        verbose_name_plural = 'Registros'
        unique_together = (('student', 'discipline'),)
        ordering = ['-join']



    student = models.ForeignKey('accounts.User', verbose_name='Aluno', on_delete=models.DO_NOTHING)
    discipline = models.ForeignKey('Discipline', verbose_name='Disciplina', on_delete=models.DO_NOTHING)
    status = models.IntegerField('Situação', choices=STATUS_CHOICE, default=0)
    join = models.DateTimeField('Registrado', auto_now_add=True)

discipline/forms.py
from django import forms

from .models import Discipline,RegisterStudent

class DisciplineForm(forms.ModelForm):
    class Meta:
        model = Discipline
        fields = '__all__'

class RegisterStudentForm(forms.ModelForm):
    class Meta:
        model = RegisterStudent
        fields = '__all__'

discipline/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from discipline.models import Discipline, RegisterStudent
from discipline.forms import DisciplineForm, RegisterStudentForm

from post.models import Topic, Reply

# Create your views here.
@login_required
def addDiscipline(request):

    if request.user.is_teacher == False:
        return redirect('error')

    success = False
    if request.method == 'POST':
        form = DisciplineForm(request.POST)
        if form.is_valid:
            form.save()
            sucess = True
        else:
            print(form.errors)

    else:
        form = DisciplineForm()

    return render(request, 'discipline/add-discipline.html', {'form': form})

class ListDisciplineView(LoginRequiredMixin, object):

    def __call__(self, request):



        if request.method == 'POST':
            form = RegisterStudentForm(request.POST)

            if form.is_valid:
                form.save()
            else:
                print(form.errors)
        else:
            form = RegisterStudentForm()

        context = {
            'form': RegisterStudentForm,
            'disciplines': Discipline.objects.all(),
            'registers': RegisterStudent.objects.get_queryset().filter(student=request.user),

        }

        return render(request, 'discipline/list-disciplines.html', context)

listDiscipline = ListDisciplineView()

class ManagerDisciplineView(LoginRequiredMixin, object):

    def __call__(self, request):

        if request.user.is_teacher == False:
            return redirect('error')


        context = {
            'disciplines': Discipline.objects.all(),
            # 'disciplines': Discipline.objects.get_queryset().filter(id=request.user.id),
        }

        return render(request, 'discipline/manager-discipline.html', context)

managerDiscipline = ManagerDisciplineView()


class ListStudentView(LoginRequiredMixin, object):

    def __call__(self, request):

        if request.user.is_teacher == False:
            return redirect('error')

        context = {
            'form': RegisterStudentForm,
            'registers': RegisterStudent.objects.all(),
        }

        return render(request, 'discipline/manager-student.html', context)

listStudent = ListStudentView()



class RegisterStudentView(LoginRequiredMixin, object):

    def __call__(self, request, id):

        if request.user.is_teacher == False:
            return redirect('error')

        student = get_object_or_404(RegisterStudent, id=id)
        form = RegisterStudentForm(data=request.POST, instance=student)

        if form.is_valid():
            form.save();
            return redirect('discipline:listStudent')


registerStudent = RegisterStudentView()

class EditDisciplineView(LoginRequiredMixin, object):

    def __call__(self, request, id):


        if request.user.is_teacher == False:
            return redirect('error')

        discipline = get_object_or_404(Discipline, id=id)
        if request.method == 'POST':
            form = DisciplineForm(data=request.POST, instance=discipline)
            if form.is_valid():
                form.save()
                return redirect('discipline:managerDiscipline')
        else:
            form = DisciplineForm(instance=discipline)

        context = {
            'form': form,
            'edit': 'edit',
        }

        return render(request,'discipline/add-discipline.html', context)

editDiscipline = EditDisciplineView()

def deleteDiscipline(LoginRequiredMixin, request, id):

    if request.user.is_teacher == False:
        return redirect('error')

    topics = Topic.objects.get_queryset().filter(id=id).delete()
    reply = Reply.objects.get_queryset().filter(id=id).delete()
    discipline = Discipline.objects.get(id=id).delete()


    return redirect('discipline:managerDiscipline')

discipline/templates/discipline/add-discipline.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block container %}

<div class="container margin-top">
  <p class="display-4">
    {% if edit %}
        Editar Disciplina
      {% else %}
        Cadastro de Disciplina
    {% endif %}
  </p>


  <form class="form-group" action="" method="post">
    {% csrf_token %}
      {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}


      <input name="teacher" id='id_teacher' value='{{ request.user.id }}' hidden/>

      <div class="form-group">
        <label for="">Nome da Disciplina</label>
        {% render_field form.name class='form-control' placeholder='Matemática' %}
      </div>

      <div class="form-group">
        <label for="">Descrição da Disciplina</label>
        {% render_field form.description class='form-control' rows="20" cols="20" placeholder='Desenvolver capacidades do aluno de observação e representação dos objetos geométricos e físicos. Fazer com que eles possam progredir na aquisição de vocabulário preciso em geometria. Fornecer ao aluno, uma bagagem de conhecimento que lhes permita resolver problemas colocados na vida corrente ou em outras disciplinas. Incitá-los ao rigor lógico nos pensamentos dedutivo e indutivo.' %}
      </div>


      {% endwith %}


  <button type="submit" class="btn btn-success">
    {% if edit %}
        Editar Disciplina
      {% else %}
        Cadastrar Disciplina
    {% endif %}
  </button>
  </form>
</div>


{% endblock %}

discipline/templates/discipline/list-disciplines.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block container %}

  <div class="container margin-top">

    <p class="display-4">Disciplinas Disponíveis</p>




    {% for discipline in disciplines %}


        <div class="card bg-light">
          {% for register in registers %}
          {% if register.discipline.id == discipline.id and register.status == 0 %}<span class="badge badge-pill badge-warning">Solicitação Pendente</span>{% endif %}
          {% if register.discipline.id == discipline.id and register.status == 1 %}<span class="badge badge-pill badge-success">Cadastrado</span>{% endif %}
          {% if register.discipline.id == discipline.id and register.status == 2 %}<span class="badge badge-pill badge-danger">Banido</span>{% endif %}
          {% if register.discipline.id == discipline.id and register.status == 3 %}<span class="badge badge-pill badge-primary">Moderador</span>{% endif %}

          {% endfor %}

          <div class="card-header bg-transparent border-info">
            <img src="{{discipline.teacher.avatar|thumbnail_url:'avatar'}}" alt="" class="rounded-circle">
             <strong>Mantido por {{discipline.teacher}}</strong>
           </div>
        <div class="card-body">
          <h5 class="card-title"><strong>{{discipline.name}}</strong></h5>
          <p class="card-text">{{discipline.description}}</p>
        </div>
        <div class="card-footer bg-transparent border-info">
          <form class="" action="" method="post">
            {% csrf_token %}
            {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}


            <input name="student" id='id_student' value='{{ request.user.id }}' hidden/>
            <input name="discipline" id='id_discipline' value='{{ discipline.id }}' hidden/>
            <input name="status" id='id_status' value='0' hidden/>


            {% endwith %}

            <button type="submit" class="btn btn-success" name="button">Inscrever-se</button>

          </form>
        </div>
      </div>
      <br><br>
    {% endfor %}

    </div>

{% endblock %}

discipline/templates/discipline/manager-discipline.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block container %}

  <div class="container margin-top">

    <p class="display-4">Gerenciar Disciplinas</p>

    <table class="table table-hover">

        <thead>
          <tr>
            <th scope="col">Nome da Disciplina</th>
            <th scope="col">Descição</th>
            <th colspan="2" style="text-align: center">Ações</th>
          </tr>
        </thead>
        <tbody>

        {% for discipline in disciplines %}

          {% if discipline.teacher == user %}
            <tr>
              <th scope="row">{{discipline.name}}</th>
              <td>{{discipline.description}}</td>
              <td style="text-align: center"><a class="btn btn-secondary btn-sm" href="{% url 'discipline:editDiscipline' discipline.id %}" role="button">Editar</a></td>

            </tr>
          {% endif %}

        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-outline-success btn-lg" href="{% url 'discipline:addDiscipline' %}" role="button">Cadastrar Disciplina</a>

    </div>

{% endblock %}

discipline/templates/discipline/manager-student.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block container %}

  <div class="container margin-top">

    <p class="display-4">Gerenciar Alunos</p>

    <table class="table table-hover">

        {% if registers %}
          <thead>
            <tr>
              <th scope="col">Aluno</th>
              <th scope="col">Situação</th>
              <th scope="col" style="text-align: center">Ações</th>
              <th scope="col" style="text-align: center">Mudar Estado</th>
            </tr>
          </thead>
          <tbody>
        {% endif %}


        {% for register in registers %}
        {% if register.discipline.teacher == user %}
          <tr>
            <td>
               <img src="{{register.student.avatar|thumbnail_url:'avatar'}}" alt="" class="rounded-circle">
            </td>
            <td >
              {{register.student}}
            </td>
            <td>

              {% if register.status == 0 %}  <p class="text-warning"><strong>Solicitação Pendente em{% endif %}
                {% if register.status == 1 %}  <p class="text-success"><strong>Aluno de{% endif %}
                  {% if register.status == 2 %}  <p class="text-danger"><strong>Banido de{% endif %}
                    {% if register.status == 3 %}  <p class="text-primary"><strong>Moderador de{% endif %}
                      {{register.discipline}}</strong></p>

                    </td>
                    <td style="text-align: center">
                      <form class="" action="{% url 'discipline:registerStudent' register.id %}" method="post">
                        {% csrf_token %}
                        {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

                        <input name="student" id='id_student' value='{{ register.student.id }}' hidden/>
                        <input name="discipline" id='id_discipline' value='{{ register.discipline.id }}' hidden/>

                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                          <label class="btn btn-primary{% if register.status == 1 %} active{% endif %}">
                            <input type="radio" name="status" id="id_status" autocomplete="off" value='1'> Tornar Aluno
                          </label>
                          <label class="btn btn-primary{% if register.status == 2 %} active{% endif %}">
                            <input type="radio" name="status" id="id_status" autocomplete="off" value='2'>  Banir Aluno
                          </label>

                          <label class="btn btn-primary{% if register.status == 3 %} active{% endif %}">
                            <input type="radio" name="status" id="id_status" autocomplete="off" value='3'> Tornar Moderador
                          </label>
                        </div>

                        <td style="text-align: center">
                          <input type="submit" name="" value="Mudar Estado" class="btn btn-primary btn-lg">
                        </td>
                        {% endwith %}
                      </form>

                    </td>
                  </tr>


        {% endif %}
        {% endfor %}


      </tbody>
    </table>

    </div>

{% endblock %}