accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('novo-usuario/', views.addUser, name='addUser'),
    path('minha-conta/', views.myAccount, name='myAccount'),
    path('atualizar-dados/', views.updateUser, name='updateUser'),
    path('atualizar-senha/', views.updatePassword, name='updatePassword'),

]

discipline/urls.py
from django.urls import path

from . import views

app_name = 'discipline'
urlpatterns = [
    path('ver-disciplinas/', views.listDiscipline, name="listDiscipline"),

    path('adicionar-disciplina/', views.addDiscipline, name="addDiscipline"),
    path('mudar-estado/(?P<id>[0-9]+)/', views.registerStudent, name="registerStudent"),
    path('editar-disciplina/(?P<id>[0-9]+)/', views.editDiscipline, name="editDiscipline"),
    path('gerenciar-alunos/', views.listStudent, name="listStudent"),
    path('gerenciar-disciplina/', views.managerDiscipline, name="managerDiscipline"),
    path('deletar-disciplina/(?P<id>[0-9]+)/', views.deleteDiscipline, name="deleteDiscipline"),

]

iscool/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static

from core import views
from post import urls as post_urls
from accounts import urls as accounts_urls
from discipline import urls as discipline_urls
from material import urls as material_urls

urlpatterns = [
    path('',views.index, name='index'),
    path('erro',views.erro404, name='error'),

    path('admin/', admin.site.urls),
    path('postar/',include(post_urls)),
    path('conta/',include(accounts_urls)),
    path('disciplina/',include(discipline_urls)),
    path('material/',include(material_urls)),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'login'}, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

material/urls.py
from django.urls import path

from . import views

app_name = 'material'
urlpatterns = [
    path('adicionar-material/', views.addMaterial, name='addMaterial'),
    path('listar-materiais/', views.listMaterial, name='listMaterial'),
    path('editar-material/(?P<id>[0-9]+)/', views.editMaterial, name="editMaterial"),
    path('deletar-material/(?P<id>[0-9]+)/', views.deleteMaterial, name="deleteMaterial"),


]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [

    path('novo-topico/', views.newTopic, name="newTopic"),
    path('nova-resposta/', views.newReply, name="newReply"),
    path('editar-topico/(?P<id>[0-9]+)/', views.editTopic, name="editTopic"),
    path('editar-comentario/(?P<id>[0-9]+)/', views.editReply, name="editReply"),
    path('deletar-topico/(?P<id>[0-9]+)/', views.deleteTopic, name="deleteTopic"),
    path('deletar-comentario/(?P<id>[0-9]+)/', views.deleteReply, name="deleteReply"),

]

core/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):

    title = models.CharField('Título', max_length=100)
    content = models.TextField('Conteúdo')
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)
    discipline = models.ForeignKey('discipline.Discipline', verbose_name='Disciplina', on_delete=models.PROTECT)
    is_warning = models.BooleanField('Aviso', default=False)
    author = models.ForeignKey('accounts.User', verbose_name='Autor', on_delete=models.PROTECT)


    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-created']

    def __str__(self):
        return self.title

class Reply(models.Model):

    content = models.TextField('Comentário')
    topic = models.ForeignKey('post.Topic', verbose_name='Tópico', on_delete=models.PROTECT)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)
    author = models.ForeignKey('accounts.User', verbose_name='Autor', on_delete=models.PROTECT)


    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'

    def __str__(self):
        return self.content

post/forms.py
from django import forms

from .models import Topic, Reply

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = '__all__'

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from post.models import Topic, Reply
from discipline.models import RegisterStudent, Discipline
from post.forms import TopicForm, ReplyForm



# Create your views here.
#
# def index(request, sucess=False):
#
#     form = TopicForm()
#
#     context = {
#         'topics': Topic.objects.all(),
#         'replies': Reply.objects.all(),
#         'form': form,
#         'sucess': sucess,
#     }
#     return render(request, 'index.html', context)
@login_required
def index(request, sucess=False ):

    formReply = ReplyForm()
    formTopic = TopicForm()

    context = {
        'topics': Topic.objects.all(),
        'replies': Reply.objects.all(),
        'disciplines': Discipline.objects.all(),
        'registers': RegisterStudent.objects.all(),
        'formReply': formReply,
        'formTopic': formTopic,
        'sucess': sucess,
    }

    return render(request, 'index.html', context)

def erro404(request):

    return render(request,'404.html')

post/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse

from post.models import Topic, Reply

from post.forms import TopicForm, ReplyForm

from core.views import index

from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def newTopic(request):

    form = TopicForm(request.POST or None)
    if form.is_valid:
        form.save()
        sucess = True
    else:
        print(form.errors)

    return redirect('index')

@login_required
def newReply(request):

    form = ReplyForm(request.POST or None)
    if form.is_valid:
        form.save()
        sucess = True
    else:
        print(form.errors)

    return redirect('index')

    # return HttpResponse(index(request,sucess))

class editTopicView(object):

    def __call__(self, request, id):

        topic = get_object_or_404(Topic, id=id)
        if request.method == 'POST':
            form = TopicForm(data=request.POST, instance=topic)
            if form.is_valid():
                form.save()
                return redirect('index')
        else:
            form = TopicForm(instance=topic)

        context = {
            'form': form,
        }

        return render(request, 'post/edit-topic.html', context)

editTopic = editTopicView()

class editReplyView(object):

    def __call__(self, request, id):

        reply = get_object_or_404(Reply, id=id)
        if request.method == 'POST':
            form = ReplyForm(data=request.POST, instance=reply)
            if form.is_valid():
                form.save()
                return redirect('index')
        else:
            form = ReplyForm(instance=reply)

        context = {
            'form': form,
        }

        return render(request, 'post/edit-reply.html', context)

editReply = editReplyView()

def deleteTopic(request, id):
    topic = Topic.objects.get(id=id).delete()
    return redirect('index')

def deleteReply(request, id):
    reply = Reply.objects.get(id=id).delete()
    return redirect('index')

core/templates/base.html
<!doctype html>
{% load static %}

<html lang="pt">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/extra.css' %}">

  <link rel="icon" href="{% static "img/favicon.ico" %}">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!--Custom CSS-->

  <title>{% block title %}isCool{% endblock %}</title>
</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container d-flex justify-content-between">

    <a class="navbar-brand" href="/">

      <img src="{% static "img/logo_index.png" %}" width="90" height="28" class="d-inline-block align-top" alt="">

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Início <span class="sr-only">(current)</span></a>
          </li>



      {% if user.is_teacher %}
      <li class="nav-item">

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Materiais</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'material:addMaterial' %}">Cadastrar Material</a>
              <a class="dropdown-item" href="{% url 'material:listMaterial' %}">Gerenciar Materiais</a>

            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Disciplinas</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'discipline:addDiscipline' %}">Cadastrar Disciplina</a>
              <a class="dropdown-item" href="{% url 'discipline:managerDiscipline' %}">Gerenciar Disciplinas</a>

            </div>
          </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'material:listMaterial' %}">Acessar Material</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'discipline:listDiscipline' %}">Buscar Disciplinas</a>
      </li>
      {% endif %}


        </li>
        <li class="nav-item">
      <li class="nav-item">


        </li>
        {% if user.is_teacher == True %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'discipline:listStudent' %}">Gerenciar Alunos</a>
          </li>

        {% endif %}

      </ul>
        <div class="nav-item dropdown">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            olá, {{user.get_short_name}}
         </button>
          <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 44px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" href="{% url 'accounts:myAccount' %}">Minha Conta</a>

            <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
          </div>
        </div>
      </div>
    </div>
  </nav>


  {% block container %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

core/templates/index.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load thumbnail %}


{% block container %}

  <div class="container margin-top">

    <div class="card border-primary">
      <div class="card-body">


        <ul class="nav nav-tabs nav-justified" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#postar_topico" role="tab" aria-controls="home" aria-selected="true">Postar Tópico</a>
          </li>

          {% if user.is_teacher == True %}
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#postar_aviso" role="tab" aria-controls="profile" aria-selected="false">Postar Aviso</a>
            </li>
          {% endif %}

        </ul>

        <div class="tab-content">

          <div class="tab-pane fade show active" id="postar_topico" role="tabpanel" >

            <form class="" action="{% url 'post:newTopic' %}" method="post">
              {% csrf_token %}

              {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

              <div class="form-group">
                {% render_field formTopic.title class='form-control' placeholder='Titulo do tópico' %}
              </div>

              <div class="form-group">
                <select id="id_discipline" name="discipline" class="form-control">

                  {% for discipline in disciplines %}

                    {% if discipline.teacher == user  %}
                      <option value="{{discipline.id }}">{{discipline.name}}</option>
                    {% endif %}

                    {% for register in registers %}
                      {% if user == register.student and register.status == 1 and register.discipline == discipline or user == register.student and register.status == 3 and register.discipline == discipline %}

                        <option value="{{discipline.id }}">{{discipline.name}}</option>

                        {% endif %}
                      {% endfor %}
                    {% endfor %}

                </select>

              </div>

              <div class="form-group">
                {% render_field formTopic.content class='form-control' rows="5" cols="20" placeholder='Conteudo do seu Tópico' %}
              </div>

                <input name="author" id='id_author' value='{{ request.user.id }}' hidden/>
              {% endwith %}
              <button type="submit" class="btn btn-primary">Postar</button>

            </form>

          </div>

          <div class="tab-pane fade" id="postar_aviso" role="tabpanel" aria-labelledby="profile-tab">

            <form class="" action="{% url 'post:newTopic' %}" method="post">
              {% csrf_token %}

              {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

              <div class="form-group">
                {% render_field formTopic.title class='form-control' placeholder='Titulo do Aviso' %}
              </div>

              <div class="form-group">
                <select id="id_discipline" name="discipline" class="form-control">

                  {% for discipline in disciplines %}

                    {% if discipline.teacher == user  %}
                      <option value="{{discipline.id }}">{{discipline.name}}</option>
                    {% endif %}

                    {% for register in registers %}
                      {% if user == register.student and register.status == 1 and register.discipline == discipline or user == register.student and register.status == 3 and register.discipline == discipline %}

                        <option value="{{discipline.id }}">{{discipline.name}}</option>

                        {% endif %}
                      {% endfor %}
                    {% endfor %}



                </select>

              </div>

              <div class="form-group">
                {% render_field formTopic.content class='form-control' rows="5" cols="20" placeholder='Conteudo do seu Aviso' %}
              </div>

                <input name="author" id='id_author' value='{{ request.user.id }}' hidden/>
                <input name="is_warning" id='is_warning' value='True' hidden/>

              {% endwith %}
              <button type="submit" class="btn btn-warning">Postar</button>

            </form>


          </div>

        </div>




        </div>
      </div>
  </div>

{% for topic in topics  %}
    {% if topic.discipline.teacher == user %}
      {% include "posts.html" %}
    {% endif %}
{% endfor %}


{% for topic in topics %}
  {% for register in registers %}
    {% if user == register.student and register.status == 1  and register.discipline == topic.discipline or user == register.student and register.status == 3 and register.discipline == topic.discipline %}
      {% include "posts.html" %}
    {% endif %}
  {% endfor %}
{% endfor %}

{% endblock %}

core/templates/posts.html
{% load widget_tweaks %}
{% load thumbnail %}


<div class="modal fade" id="modal{{topic.id}}" tabindex="-1" role="dialog" aria-labelledby="modal{{topic.id}}Label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal{{topic.id}}Label1">{{ topic }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="container-fluid">
          <div class="row">
            <div class="col">
              <p class="lead">{{ topic.content|escape }}</p>
              <div class="row">

                <div class="col">
                  <form class="" action="{% url 'post:newReply' %}" method="post">

                    {% csrf_token %}

                    <div class="form-group">
                      {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

                      {% render_field formReply.content rows="3" class="form-control" placeholder="Insira uma resposta aqui" %}

                      {% endwith %}

                      {# {{ formReply.content| add_class:"form-control"|placeholder:"oi"}} #}
                    </div>

                    <input name="topic" id='id_topic' value='{{ topic.id }}' hidden/>
                    <input name="author" id='id_author' value='{{ request.user.id }}' hidden/>



                    <button type="submit" class="btn btn-secondary">Comentar</button>

                  </form>



                  <table class="table table-hover table-active">
                    <tbody>

                      {% for reply in replies %}
                      {% if reply.topic.id == topic.id %}
                      <tr>
                        <td>
                          <img src="{{reply.author.avatar|thumbnail_url:'avatar'}}" alt="" class="rounded-circle">
                          <strong>{{reply.author.get_short_name}} respondeu</strong>
                          <p class="lead">{{reply.content}}</p>
                          {% if user == register.student and register.status == 3  and register.discipline == topic.discipline or user == reply.author or topic.discipline.teacher == user %}

                            <a class="btn btn-secondary btn-sm" href="{% url 'post:editReply' reply.id %}" role="button">Editar</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'post:deleteReply' reply.id %}" role="button">Deletar</a>

                          {% endif %}
                        </td>
                      </tr>

                      {% endif %}
                      {% endfor %}

                    </tbody>
                  </table>


                </div>
              </div>


            </div>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

<br>

<div class="container">

  <div class="{% if topic.is_warning == True %}card border-warning mb-3{% else %}card{% endif %}">
    <div class="card-header font-weight-bold">
      <img src="{{topic.author.avatar|thumbnail_url:'avatar'}}" alt="" class="rounded-circle">
      Postado por {{topic.author.get_short_name}}
    </div>


    <div class="{% if topic.is_warning == True %}card-body text-warning{% else %}card-body{% endif %}">
      <h4 class="card-title">{{topic.title}}</h4>
      <div class="card-text"><p class="lead"> {{ topic.content|linebreaks }} </p></div>
      <div class="row">

        {% if topic.is_warning == False %}
          <button type="button" class="btn btn-outline-primary display-2" data-toggle="modal" data-target="#modal{{topic.id}}">Ler Comentários</button>
        {% endif %}

        {% if topic.author == request.user or user == register.student and register.status == 3  and register.discipline == topic.discipline or topic.discipline.teacher == user %}
        <a class="btn btn-secondary btn-sm" href="{% url 'post:editTopic' topic.id %}" role="button">Editar</a>
        <a class="btn btn-secondary btn-sm" href="{% url 'post:deleteTopic' topic.id %}" role="button">Deletar</a>
        {% endif %}
      </div>

    </div>

    <div class="card-footer ">
      <h5><a href="#" class="badge badge-info">{{ topic.discipline }}</a></h5>





    </div>

  </div>

</div>

{# temporario #}
<br>