iscool/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static

from core import views
from post import urls as post_urls
from accounts import urls as accounts_urls
from discipline import urls as discipline_urls
from material import urls as material_urls

urlpatterns = [
    path('',views.index, name='index'),
    path('erro',views.erro404, name='error'),

    path('admin/', admin.site.urls),
    path('postar/',include(post_urls)),
    path('conta/',include(accounts_urls)),
    path('disciplina/',include(discipline_urls)),
    path('material/',include(material_urls)),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'login'}, name='logout'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

material/urls.py
from django.urls import path

from . import views

app_name = 'material'
urlpatterns = [
    path('adicionar-material/', views.addMaterial, name='addMaterial'),
    path('listar-materiais/', views.listMaterial, name='listMaterial'),
    path('editar-material/(?P<id>[0-9]+)/', views.editMaterial, name="editMaterial"),
    path('deletar-material/(?P<id>[0-9]+)/', views.deleteMaterial, name="deleteMaterial"),


]

post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [

    path('novo-topico/', views.newTopic, name="newTopic"),
    path('nova-resposta/', views.newReply, name="newReply"),
    path('editar-topico/(?P<id>[0-9]+)/', views.editTopic, name="editTopic"),
    path('editar-comentario/(?P<id>[0-9]+)/', views.editReply, name="editReply"),
    path('deletar-topico/(?P<id>[0-9]+)/', views.deleteTopic, name="deleteTopic"),
    path('deletar-comentario/(?P<id>[0-9]+)/', views.deleteReply, name="deleteReply"),

]

material/models.py
from django.db import models

# Create your models here.

class Material(models.Model):

    discipline = models.ForeignKey('discipline.Discipline', verbose_name='Disciplina', on_delete=models.PROTECT)
    name = models.CharField('Nome', max_length=50)
    description = models.TextField('Descição', blank=True)
    file = models.FileField('Material', upload_to='materials')
    shared_by = models.ForeignKey('accounts.User', verbose_name='Compartilhado por', on_delete=models.PROTECT)



    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'

material/forms.py
from django import forms

from .models import Material

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = '__all__'

material/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.contrib.auth.decorators import login_required

from discipline.models import Discipline, RegisterStudent
from .models import Material
from .forms import MaterialForm

# Create your views here.

@login_required
def addMaterial(request):

    if request.user.is_teacher == False:
        return redirect('error')

    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            sucess = True
        else:
            print(form.errors)

    else:
        form = MaterialForm()

    context = {
        'form': MaterialForm,
        'disciplines': Discipline.objects.all(),
    }

    return render(request, 'material/add-material.html', context)

def listMaterial(request):

    context = {
        'materials': Material.objects.all(),
        'registers': RegisterStudent.objects.all(),
    }

    return render(request, 'material/list-material.html', context)

def editMaterial(request, id):

    if request.user.is_teacher == False:
        return redirect('error')

    material = get_object_or_404(Material, id=id)
    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES, instance=material)
        if form.is_valid():
            form.save()
            return redirect('material:listMaterial')
    else:
        form = MaterialForm(instance=material)

    context = {
        'form': form,
        'edit': 'edit',
        'material': material,
    }

    return render(request,'material/add-material.html', context)

def deleteMaterial(request, id):

    if request.user.is_teacher == False:
        return redirect('error')

    material = Material.objects.get(id=id).delete()

    return redirect('material:listMaterial')

material/templates/material/add-material.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block container %}

<div class="container margin-top">
  <p class="display-4">
    {% if edit %}
        Editar Material
      {% else %}
        Cadastro de Material
    {% endif %}
  </p>


  <form class="form-group" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {% with WIDGET_ERROR_CLASS='my_error' WIDGET_REQUIRED_CLASS='my_required' %}

      <input name="shared_by" id='id_shared_by' value='{{ request.user.id }}' hidden/>

      {% if material %}

        <input type="hidden" id="id_discipline" name="discipline" value="{{material.discipline.id}}">

      {% else %}

        <div class="form-group">

          <select id="id_discipline" name="discipline" class="form-control">
            {% for discipline in disciplines %}
            {% if user == discipline.teacher %}

            <option value="{{discipline.id }}">{{discipline.name}}</option>

            {% endif %}
            {% endfor %}
          </select>

        </div>


      {% endif %}


      <div class="form-group">
        <label for="">Nome do Material</label>
        {% render_field form.name class='form-control' placeholder='Exemplo: Slides de Matemática' %}
      </div>

      <div class="form-group">
        <label for="">Descição do Material</label>
        {% render_field form.description class='form-control' placeholder='Breve Descição' rows="5" %}
      </div>

      <div class="form-group">
        <label for="">Selecione o Material</label>
        {% render_field form.file class='form-control' %}
      </div>


      {% endwith %}


  <button type="submit" class="btn btn-success">
    {% if edit %}
        Editar Material
      {% else %}
        Cadastrar Material
    {% endif %}
  </button>
  </form>
</div>


{% endblock %}

material/templates/material/list-material.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load thumbnail %}

{% block container %}

<div class="container margin-top">

  <p class="display-4">
    {% if user.is_teacher %}
      Gerenciar Materiais
      {% else %}
      Materiais Compartilhados
    {% endif %}

  </p>

{% for material in materials %}
  {% if material.shared_by == user %}
    <div class="card border-dark mb-3" >
      <div class="card-header">
        <strong>Disciplina de {{material.discipline}}</strong>
      </div>
        <div class="card-body text-dark text-center">
          <h4 class="card-title">{{material.name}}</h4>
          <p class="card-text">{{material.description}}</p>
          <a href="{{material.file.url}}" class="btn btn-info btn-sm" download>Baixar</a>
          <a href="{% url 'material:editMaterial' material.id %}" class="btn btn-secondary btn-sm">Editar</a>
          <a href="{% url 'material:deleteMaterial' material.id %}" class="btn btn-danger btn-sm">Editar</a>

        </div>
      </div>

  {% endif %}
{% endfor %}


  {% for material in materials  %}
    {% for register in registers %}

      {% if register.student == user and material.discipline == register.discipline %}

        <div class="card border-dark mb-3" >
          <div class="card-header">

            <img src="{{material.shared_by.avatar|thumbnail_url:'avatar'}}" alt="" class="rounded-circle">
            Compartilhado por {{material.shared_by}}</div>
          <div class="card-body text-dark text-center">
            <h4 class="card-title">{{material.name}}</h4>
            <p class="card-text">{{material.description}}</p>
            <a href="{{material.file.url}}" class="btn btn-info" download>Baixar</a>
          </div>
        </div>

        {% endif %}

    {% endfor %}

  {% endfor %}


</div>


{% endblock %}